[package]
name = "compiler_judge"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
lazy_static = "1.5.0"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
